name: Selenium UI Test

on:
  push:
  pull_request:

jobs:
  ui-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Start test server
        run: |
          nohup python3 -m http.server 8000 &
          sleep 2

      - name: Run Selenium tests
        run: python3 tests/first_test.py
